#!/usr/bin/env ruby
require './app'

class Main
  def initialize
    @app = App.new
  end

  def interface
    puts "Welcome to School Library App!\n\n"
    puts 'Please choose an option by entering a number:'
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
    option
  end
end

Main.new.interface
